### ISSUE TITLE
I encountered an error while replicating the dismod_MR tool

### ISSUE THREAD

**Issue by yannie228** [ihmeuw/dismod_mr#36]
I hope to get your help. The error is as follows:
![图片 1](https://user-images.githubusercontent.com/51351505/191713142-2cd64360-f8d6-4193-b19f-1f47440fda7e.png)

**Comment by aflaxman** [comment]
I'm sorry to hear that you are having trouble using the dismod_mr tool.  I can't tell what is going wrong from this screenshot alone.  Can you produce a "minimal complete verifiable example" of the issue you are having? https://stackoverflow.com/help/minimal-reproducible-example

**Comment by yannie228** [comment]
Thanks for your prompt reply, maybe you can try running this ipynb file with your pd_sim_data folder？
[DisMod-MR 2.1-Copy1.ipynb.zip](https://github.com/ihmeuw/dismod_mr/files/9631085/DisMod-MR.2.1-Copy1.ipynb.zip)

**Comment by aflaxman** [comment]
I had a little trouble getting the data to load (I had to change the directory to get `dismod_mr.data.load('pd_sim_data')` to succeed, but everything else in your notebook worked fine for me.  Please try re-running everything in a fresh conda environment, following the directions on the [README.md](https://github.com/ihmeuw/dismod_mr/blob/master/README.rst) file, and see if there is perhaps something in your current python environment that is causing this issue.

**Comment by aflaxman** [comment]
I have not had a chance to look at this, but I thought I’d send a quick reply to say that I received it.

**Comment by fanwayne** [comment]
Hello, I think I have the same issue when running the example code recently. 

The code was copied from the page "A motivating example: descriptive epidemiological meta-regression of Parkinson's Disease".

`model.vars += dismod_mr.model.asr(model, 'p')`

And below error occurs when running the asr function.

`
IndexError                                Traceback (most recent call last)
File c:\ProgramData\miniconda3\lib\site-packages\pymc\model.py:197, in ContextMeta.get_context(cls, error_if_none)
    [196](file:///c%3A/ProgramData/miniconda3/lib/site-packages/pymc/model.py?line=195) try:
--> [197](file:///c%3A/ProgramData/miniconda3/lib/site-packages/pymc/model.py?line=196)     candidate: Optional[T] = cls.get_contexts()[-1]
    [198](file:///c%3A/ProgramData/miniconda3/lib/site-packages/pymc/model.py?line=197) except IndexError as e:
    [199](file:///c%3A/ProgramData/miniconda3/lib/site-packages/pymc/model.py?line=198)     # Calling code expects to get a TypeError if the entity
    [200](file:///c%3A/ProgramData/miniconda3/lib/site-packages/pymc/model.py?line=199)     # is unfound, and there's too much to fix.

IndexError: list index out of range

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
File c:\ProgramData\miniconda3\lib\site-packages\pymc\distributions\distribution.py:276, in Distribution.__new__(cls, name, rng, dims, initval, observed, total_size, transform, *args, **kwargs)
    [274](file:///c%3A/ProgramData/miniconda3/lib/site-packages/pymc/distributions/distribution.py?line=273)     from pymc.model import Model
--> [276](file:///c%3A/ProgramData/miniconda3/lib/site-packages/pymc/distributions/distribution.py?line=275)     model = Model.get_context()
    [277](file:///c%3A/ProgramData/miniconda3/lib/site-packages/pymc/distributions/distribution.py?line=276) except TypeError:

File c:\ProgramData\miniconda3\lib\site-packages\pymc\model.py:202, in ContextMeta.get_context(cls, error_if_none)
    [201](file:///c%3A/ProgramData/miniconda3/lib/site-packages/pymc/model.py?line=200) if error_if_none:
--> [202](file:///c%3A/ProgramData/miniconda3/lib/site-packages/pymc/model.py?line=201)     raise TypeError(f"No {cls} on context stack")
    [203](file:///c%3A/ProgramData/miniconda3/lib/site-packages/pymc/model.py?line=202) return None

TypeError: No <class 'pymc.model.Model'> on context stack
...
    [283](file:///c%3A/ProgramData/miniconda3/lib/site-packages/pymc/distributions/distribution.py?line=282)     )
    [285](file:///c%3A/ProgramData/miniconda3/lib/site-packages/pymc/distributions/distribution.py?line=284) if "testval" in kwargs:
    [286](file:///c%3A/ProgramData/miniconda3/lib/site-packages/pymc/distributions/distribution.py?line=285)     initval = kwargs.pop("testval")

TypeError: No model on context stack, which is needed to instantiate distributions. Add variable inside a 'with model:' block, or use the '.dist' syntax for a standalone distribution.
`

**Comment by aflaxman** [comment]
Sorry for the challenge of getting it to work… I believe that this issue you are running into is because dismod_mr is based on an older version of pymc.  Please see if uninstalling your pymc and installing an older version makes the example work for you:
 
```
pip uninstall pymc
pip install pymc==2.3.8
```

**Comment by aflaxman** [comment]
Note also that the best python version for this is 3.6, as pymc==2.3.8 has some issues with the most current version of python (3.11). My apologies again for the challenge of getting this to work!

**Comment by fanwayne** [comment]
@aflaxman Many thanks for your support. It works fine in the local conda environment.

**Comment by xunluning** [comment]
Hello, maybe I hope to get your help, I want to learn this example--"A motivating example: descriptive epidemiological meta-regression of Parkinson's Disease", but an error occurred when clicking this link.

**Comment by xunluning** [comment]
Hello, I hope to get your help. The error is as follows:
**pred=dismod_mr.model.predict_for(model,model.parameters['p'],'all',"female",2005,'GBR','female',2005,1.,model.vars['p'],0.,1.)**
Traceback (most recent call last):
  File "D:\Anaconda\envs\dismod_mr\lib\site-packages\networkx\classes\digraph.py", line 809, in successors
    return iter(self._succ[n])
KeyError: 'GBR'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Anaconda\envs\dismod_mr\lib\code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "D:\Anaconda\envs\dismod_mr\lib\site-packages\dismod_mr\model\covariates.py", line 389, in predict_for
    leaves = [n for n in nx.traversal.bfs_tree(area_hierarchy, area) if area_hierarchy.successors(n) == []]
  File "D:\Anaconda\envs\dismod_mr\lib\site-packages\networkx\algorithms\traversal\breadth_first_search.py", line 196, in bfs_tree
    T.add_edges_from(edges_gen)
  File "D:\Anaconda\envs\dismod_mr\lib\site-packages\networkx\classes\digraph.py", line 681, in add_edges_from
    for e in ebunch_to_add:
  File "D:\Anaconda\envs\dismod_mr\lib\site-packages\networkx\algorithms\traversal\breadth_first_search.py", line 145, in bfs_edges
    for e in generic_bfs_edges(G, source, successors, depth_limit):
  File "D:\Anaconda\envs\dismod_mr\lib\site-packages\networkx\algorithms\traversal\breadth_first_search.py", line 76, in generic_bfs_edges
    queue = deque([(source, depth_limit, neighbors(source))])
  File "D:\Anaconda\envs\dismod_mr\lib\site-packages\networkx\classes\digraph.py", line 811, in successors
    raise NetworkXError("The node %s is not in the digraph." % (n,))
networkx.exception.NetworkXError: The node GBR is not in the digraph.

**Comment by aflaxman** [comment]
I bet we are getting errors with modern versions of networkx now, too :(  Can you check if your networkx version is 2.3?

**Comment by xunluning** [comment]
Thanks for your prompt reply, I have checked. Actually, the nextworkx version in my conda is 2.3.
![AA](https://github.com/user-attachments/assets/5c880f4f-ff1e-4f71-b2c6-559fdd134516)

**Comment by xunluning** [comment]
Thanks. It works successfully now. Mybe there was some error when l used 'model.keep()' command.

**Comment by aflaxman** [comment]
Yay!  Mysterious, but I'll consider it a closed case.  Please reopen if you have more trouble.
